name: jittor_comp_human
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - expat=2.7.1
  - gcc=10.4.0
  - gcc_impl_linux-64=10.4.0
  - gxx=10.4.0
  - gxx_impl_linux-64=10.4.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-devel_linux-64=10.4.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsanitizer=10.4.0
  - libstdcxx-devel_linux-64=10.4.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - astunparse==1.6.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.58.4
      - importlib-resources==6.5.2
      - jittor==1.3.9.14
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - numpy==1.26.4
      - packaging==25.0
      - pillow==11.3.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - scipy==1.13.1
      - six==1.17.0
      - tqdm==4.67.1
      - trimesh==4.6.13
      - zipp==3.23.0
      - -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

